apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: expensy-backend
  namespace: expensy
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - expensy
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: expensy-frontend
  namespace: expensy
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
      - expensy
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
